# Generated by Django 5.0.4 on 2025-03-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app_user', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff_member',
            field=models.BooleanField(default=False),
        ),
    ]
