# Generated by Django 5.0.4 on 2025-03-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app_user', '0003_customuser_is_staff_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff_member',
        ),
    ]
